export const CENTRO_ESTUDIOS_API = {
    alumnos: '/api/Alumnoes',
    apoderados: '/api/Apoderadoes',
    alumnoApoderados: '/api/AlumnoApoderadoes',
    colegios: '/api/Colegios',
    parentescos: '/api/Parentescoes',
    tipoEvaluaciones: '/api/TipoEvaluacions',
    evaluacionTipoPreguntas: '/api/EvaluacionTipoPreguntums',
    evaluacionProgramadas: '/api/EvaluacionProgramadums',
    evaluacionProgramadaSecciones: '/api/EvaluacionProgramadaSeccions',
    evaluacionDetalles: '/api/EvaluacionDetalles',
    evaluacionDetalleDefatults: '/api/EvaluacionDetalleDefatults',
    evaluacionClaves: '/api/EvaluacionClaves',
    evaluaciones: '/api/Evaluacions',
    estadoEvaluacionProgramadas: '/api/EstadoEvaluacionProgramadums',
    evaluacionProgramadaConsultas: '/consulta/evaluaciones-programadas',
} as const;
